# Generated by Django 4.1.5 on 2023-01-31 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citi', models.CharField(max_length=150, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(choices=[('selected', '-----'), ('Мастер', 'Мастер'), ('Механик', 'Механик')], max_length=100)),
                ('name_worker', models.CharField(db_index=True, max_length=150, verbose_name='Имя сотрудника')),
                ('brigades', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='Management_app.brigade', verbose_name='Сотрудники')),
            ],
        ),
        migrations.CreateModel(
            name='Object_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Имя объекта')),
                ('place_work', models.CharField(max_length=150, verbose_name='Место работ')),
                ('description', models.TextField(verbose_name='Описание работ')),
                ('type_works', models.CharField(choices=[('SERVICE', 'Техническое обслуживание'), ('REPAIR', 'Ремонт'), ('INSTALLATION', 'Монтаж'), ('ASSEMBLY', 'Сборка')], max_length=100)),
                ('status_work', models.CharField(choices=[], max_length=100)),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Время начала работ')),
                ('finishing_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания работ')),
                ('brigades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management_app.brigade', verbose_name='Бригада')),
            ],
        ),
    ]
