# Generated by Django 4.1.5 on 2023-02-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectes',
            name='finishing_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания работ'),
        ),
        migrations.AddField(
            model_name='objectes',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала работ'),
        ),
    ]
